import { ContentType, type Webcam } from '@/models/webcam'

export const webcams: Webcam[] = [
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Crevacol',
    label: 'Arrivo seggiovia testa bassa',
    altitude: '2450 m',
    contentType: ContentType.IMG,
    link: 'https://pila.it/webcams/Crevacol01.jpg',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Crevacol',
    label: 'Foyer du fond, Flassin',
    altitude: '1380 m',
    contentType: ContentType.IMG,
    link: 'https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_soyen.jpg?b28bfe58-ba16-4619-a175-167b092503c2',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    resort: 'Crevacol',
    label: 'Saint Rhémy en Bosses',
    contentType: ContentType.IMG,
    link: 'https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_crevacol.jpg?bab0fbcf-05a3-466b-a213-b31f6ab77a49',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Pila',
    label: 'Grimondet',
    altitude: '2348 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6316',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/38/6316.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Ban',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/banold',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_ban.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Sestriere',
    label: 'Monte Fraiteve',
    contentType: ContentType.IFRAME,
    link: 'https://montefraiteve.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5712/preview_og.jpg',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Col du Lautaret',
    altitude: '2058 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serrechevalier/coldulautaret',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Proel',
    altitude: '2566 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serre-chevalier/prorel',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Biancon',
    altitude: '2566 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serre-chevalier/briancon',
  },
]
