import { ContentType, type Webcam } from '@/models/webcam'

export const webcams: Webcam[] = [
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Crevacol',
    label: 'Arrivo seggiovia testa bassa',
    altitude: '2450 m',
    contentType: ContentType.IMG,
    link: 'https://pila.it/webcams/Crevacol01.jpg',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Crevacol',
    label: 'Foyer du fond, Flassin',
    altitude: '1380 m',
    contentType: ContentType.IMG,
    link: 'https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_soyen.jpg',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle del Gran San Bernardo',
    resort: 'Crevacol',
    label: 'Saint Rhémy en Bosses',
    contentType: ContentType.IMG,
    link: 'https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_crevacol.jpg',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Grimondet',
    altitude: '2348 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6316',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/38/6316.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Chamolé',
    altitude: '2301 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6312',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/38/6312.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Grimod',
    altitude: '2157 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6311',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/37/6311.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Baby Gorraz',
    altitude: '1866 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6315',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/37/6315.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Fun Park',
    altitude: '1757 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?design=v3&cam=6314',
    thumbnailLink: 'https://wtvpict.feratel.com/picture/37/6314.jpeg?&design=v3',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: 'Pila',
    label: 'Snowpark AreaEffe',
    altitude: '1757 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skylinewebcams.com/webcam/italia/valle-daosta/aosta/snowpark-areaeffe.html?w=390',
    thumbnailLink: 'https://embed.skylinewebcams.com/media.php?id=390&w=450',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Ban',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/banold',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_ban.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: '6 Gigante',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/ban',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_gigante.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Selletta',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/sellette',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_selette.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Campo Smith',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/campo-smith-1',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_campo-smith-1.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Chesal',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/chesal-panoramique',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_chesal-panoramique.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Pian del sole',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/pian-del-sol',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_plan-del-sol.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Bardonecchia',
    label: 'Vallon Cross',
    contentType: ContentType.IFRAME,
    link: 'https://app.webcam-hd.com/bardonecchia/vallon_cros',
    thumbnailLink: 'https://www.trinum.com/ibox/ftpcam/small_bardonecchia_vallon-cros.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Sestriere',
    label: 'Tappeti Jolly',
    contentType: ContentType.IFRAME,
    link: 'https://tappetijolly.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5861/preview_og.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Sansicario',
    label: 'Roccia Rotonda',
    contentType: ContentType.IFRAME,
    link: 'https://rocciarotonda.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5715/preview_og.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: "Vialattea - Sause d'oulx",
    label: 'Monte Triplex',
    contentType: ContentType.IFRAME,
    link: 'https://montetriplex.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5858/preview_og.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Sestriere',
    label: 'Monte Fraiteve',
    contentType: ContentType.IFRAME,
    link: 'https://montefraiteve.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5712/preview_og.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Claviere',
    label: 'Colle Bercia',
    contentType: ContentType.IFRAME,
    link: 'https://collebercia.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5706/preview_og.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val di Susa',
    resort: 'Vialattea - Sestriere',
    label: 'Area Banchetta',
    contentType: ContentType.IFRAME,
    link: 'https://areabanchetta.panomax.com/',
    thumbnailLink: 'https://live-image.panomax.com/cams/5709/preview_og.jpg',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Col du Lautaret',
    altitude: '2058 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serrechevalier/coldulautaret',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Proel',
    altitude: '2566 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serre-chevalier/prorel',
  },
  {
    nation: 'FRA',
    region: "Provence-Alpes-Côte d'Azur",
    subRegion: 'Hautes-Alpes',
    resort: 'Serre Chevalier',
    label: 'Biancon',
    altitude: '2566 m',
    contentType: ContentType.IFRAME,
    link: 'https://www.skaping.com/serre-chevalier/briancon',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: "Val d'Ayas",
    resort: 'Monterosa Ski',
    label: 'Antagnod',
    altitude: '1730 m',
    contentType: ContentType.IMG,
    link: 'https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_antagnod.jpg',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val Sesia',
    resort: 'Monterosa Ski',
    label: 'Arrivo seggiovia Cimalegna',
    altitude: '3030 m',
    contentType: ContentType.IMG,
    link: 'https://www.monterosa2000.it/webcam/Mosso/607/Mosso.jpg?id=208298',
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Val Sesia',
    resort: 'Monterosa Ski',
    label: 'Bacino Mullero',
    altitude: '2150 m',
    contentType: ContentType.IMG,
    link: 'https://www.monterosa2000.it/webcam/Lago/102/Lago.jpg?id=529228',
  },
  {
    nation: 'ITA',
    region: "Valle d'Aosta",
    subRegion: 'Valle di Gressoney',
    resort: 'Monterosa Ski',
    label: 'Bettaforca',
    altitude: '2730 m',
    contentType: ContentType.IFRAME,
    link: 'https://webtv.feratel.com/webtv/?cam=6283&t=1&design=v4&c0=0&c2=1&c39=0&c40=0&lg=it&s=0&c1=0',
    thumbnailLink: 'https://wtvpano.feratel.com/pano/11/6283.jpeg?timestamp=1734456659441',
  },
]
